let hoopers = [
  {
    id: 1,
    name: "Kenny",
    location: "Garden Grove",
    picture: "kenny.jpg",
    quote: "im gonna cross u up so bad lol",
    stats: {
      shooting: 4,
      passing: 3,
      conviction: 10,
      rebounds: 8,
      defence: 8,
      mental: 3,
      driving: 7,
    },
  },
  {
    id: 2,
    name: "Timmy",
    location: "Garden Grove",
    picture: "tim.jpg",
    quote: "just gotta shoot better haha",
    stats: {
      shooting: 10,
      passing: 3,
      conviction: 10,
      rebounds: 9,
      defence: 10,
      mental: 10,
      driving: 9,
    },
  },
  {
    id: 3,
    name: "Kevin",
    location: "Garden Grove",
    picture: "kevin.jpg",
    quote: "WEIGHT ROOM",
    stats: {
      shooting: 10,
      passing: 7,
      conviction: 9,
      rebounds: 10,
      defence: 10,
      mental: 5,
      driving: 10,
    },
  },
  {
    id: 4,
    name: "George",
    location: "Garden Grove",
    picture: "george.jpg",
    quote: "the kid was trash talking so i had to shut him up",
    stats: {
      shooting: 10,
      passing: 10,
      conviction: 10,
      rebounds: 10,
      defence: 9,
      mental: 8,
      driving: 8,
    },
  },
  {
    id: 5,
    name: "Roger",
    location: "Garden Grove",
    picture: "roger.jpg",
    quote: "Ill look for you 😎",
    stats: {
      shooting: 8,
      passing: 10,
      conviction: 6,
      rebounds: 10,
      defence: 10,
      mental: 7,
      driving: 5,
    },
  },
  {
    id: 6,
    name: "Han",
    location: "Garden Grove",
    picture: "han.jpg",
    quote: "ILL SHOOT FOR BALL",
    stats: {
      shooting: 8,
      passing: 6,
      conviction: 10,
      rebounds: 4,
      defence: 8,
      mental: 7,
      driving: 3,
    },
  },
  {
    id: 7,
    name: "Hieu",
    location: "Garden Grove",
    picture: "hieu.jpg",
    quote: "if we really wanna win, ill play inside",
    stats: {
      shooting: 9,
      passing: 10,
      conviction: 10,
      rebounds: 4,
      defence: 7,
      mental: 10,
      driving: 9,
    },
  },
  {
    id: 8,
    name: "Steven",
    location: "San Diego",
    picture: "steven.jpg",
    quote: "gonna drive this ball and steal yo girl",
    stats: {
      shooting: 6,
      passing: 6,
      conviction: 10,
      rebounds: 4,
      defence: 7,
      mental: 10,
      driving: 10,
    },
  },
  {
    id: 9,
    name: "Hao",
    location: "Garden Grove",
    picture: "hao.jpg",
    quote: "3 but no d",
    stats: {
      shooting: 8,
      passing: 6,
      conviction: 3,
      rebounds: 5,
      defence: 2,
      mental: 8,
      driving: 7,
    },
  },
  {
    id: 10,
    name: "Courtney",
    location: "Huntington Beach",
    picture: "courtney.jpg",
    quote: "but when are we going to edc?",
    stats: {
      shooting: 10,
      passing: 10,
      conviction: 10,
      rebounds: 10,
      defence: 10,
      mental: 10,
      driving: 10,
    },
  },
];

export default hoopers;
