let hoopers = [
  {
    name: "Kenny",
    location: "Garden Grove",
    picture: "/assets/kenny.jpg",
    quote: "im gonna cross u up so bad lol",
    stats: {
      shooting: 4,
      passing: 3,
      conviction: 10,
      rebounds: 8,
      defence: 8,
      mental: 3,
      driving: 7,
    },
  },
  {
    name: "Timmy",
    location: "Garden Grove",
    picture: "/assets/timmy.jpg",
    quote: "just gotta shoot better haha",
    stats: {
      shooting: 10,
      passing: 3,
      conviction: 10,
      rebounds: 9,
      defence: 10,
      mental: 10,
      driving: 9,
    },
  },
  {
    name: "Kevin",
    location: "Garden Grove",
    picture: "/assets/kenny.jpg",
    quote: "im gonna cross u up so bad lol",
    stats: {
      shooting: 10,
      passing: 7,
      conviction: 9,
      rebounds: 10,
      defence: 10,
      mental: 5,
      driving: 10,
    },
  },
  {
    name: "George",
    location: "Garden Grove",
    picture: "/assets/kenny.jpg",
    quote: "im gonna cross u up so bad lol",
    stats: {
      shooting: 10,
      passing: 10,
      conviction: 10,
      rebounds: 10,
      defence: 9,
      mental: 8,
      driving: 8,
    },
  },
  {
    name: "Roger",
    location: "Garden Grove",
    picture: "/assets/kenny.jpg",
    quote: "im gonna cross u up so bad lol",
    stats: {
      shooting: 8,
      passing: 10,
      conviction: 6,
      rebounds: 10,
      defence: 10,
      mental: 7,
      driving: 5,
    },
  },
  {
    name: "Han",
    location: "Garden Grove",
    picture: "/assets/kenny.jpg",
    quote: "im gonna cross u up so bad lol",
    stats: {
      shooting: 8,
      passing: 6,
      conviction: 10,
      rebounds: 4,
      defence: 8,
      mental: 7,
      driving: 3,
    },
  },
  {
    name: "Hieu",
    location: "Garden Grove",
    picture: "/assets/kenny.jpg",
    quote: "im gonna cross u up so bad lol",
    stats: {
      shooting: 9,
      passing: 10,
      conviction: 10,
      rebounds: 4,
      defence: 7,
      mental: 10,
      driving: 9,
    },
  },
  {
    name: "Steven",
    location: "Garden Grove",
    picture: "/assets/kenny.jpg",
    quote: "im gonna cross u up so bad lol",
    stats: {
      shooting: 6,
      passing: 6,
      conviction: 10,
      rebounds: 4,
      defence: 7,
      mental: 10,
      driving: 10,
    },
  },
  {
    name: "Hao",
    location: "Garden Grove",
    picture: "/assets/kenny.jpg",
    quote: "3 but no d",
    stats: {
      shooting: 8,
      passing: 6,
      conviction: 3,
      rebounds: 5,
      defence: 2,
      mental: 8,
      driving: 7,
    },
  },
  {
    name: "Courtney",
    location: "Huntington Beach",
    picture: "/assets/courtney.jpg",
    quote: "but when are we going to edc?",
    stats: {
      shooting: 10,
      passing: 10,
      conviction: 10,
      rebounds: 10,
      defence: 10,
      mental: 10,
      driving: 10,
    },
  },
];
